owner: basilesimon
repo: upptime-monitor
user-agent: basilesimon-upptime-crawler

sites:
  - name: Personal website
    url: https://basilesimon.fr
    icon: https://basilesimon.fr/public/favicon.ico
  - name: Personal blog
    url: https://blog.basilesimon.fr
    icon: https://basilesimon.fr/public/favicon.ico
  - name: Cambodia Corporates
    url: https://cambodiacorporates.globalwitness.org
    icon: https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/271/flag-cambodia_1f1f0-1f1ed.png
  - name: Great Rip Off Map
    url: https://greatripoffmap.globalwitness.org
    icon: https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/271/world-map_1f5fa-fe0f.png
  - name: Linkurious
    url: https://linkurious.globalwitness.org/login
    icon: https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/271/spider-web_1f578-fe0f.png

assignees:
  - basilesimon

status-website:
  baseUrl: /upptime-monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Status report"
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
